name: CI/CD Pipeline for Website App

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    types:
      - closed  # Trigger when a pull request is closed
    branches:
      - main  # Only trigger for pull requests targeting the main branch

env:
  IMAGE_NAME: ghcr.io/rhinohomestech/rhp-website-fe
  K8S_NAMESPACE: rhp-website-fe-ns

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install kubectl
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Create kubeconfig file
        run: |
            cat <<EOF > kubeconfig.yaml
            apiVersion: v1
            kind: Config
            clusters:
              - name: my-cluster
                cluster:
                  server: ${{ secrets.K8S_API_SERVER_URL }}  # Replace with your Kubernetes API server URL
                  insecure-skip-tls-verify: true  # Use only for testing; avoid in production
            users:
              - name: rhp-website-fe-service-account
                user:
                  token: ${{ secrets.K8S_CONFIG }}  # Use the service account token from the secret
            contexts:
              - name: my-context
                context:
                  cluster: my-cluster
                  user: rhp-website-fe-service-account
            current-context: my-context
            EOF
      # Configure kubeconfig for self-hosted cluster
      - name: Set KUBECONFIG
        run: |
          export KUBECONFIG=kubeconfig.yaml
          echo "KUBECONFIG is set to: $KUBECONFIG"

      - name: Verify kubeconfig
        run: |
            cat kubeconfig.yaml
            kubectl config view

      # Apply ConfigMap
      - name: Apply ConfigMap
        run: |
          kubectl --kubeconfig=kubeconfig.yaml apply -f rhp-website-fe-dev-configmap.yaml -n ${{ env.K8S_NAMESPACE }}


      # Replace COMMIT_SHA placeholder with the actual commit SHA
      - name: Replace COMMIT_SHA placeholder
        run: |
            sed -i "s/COMMIT_SHA/${{ github.sha }}/g" rhp-website-fe-dev-deployment-service.yaml

      # Apply Deployment and Service
      - name: Apply Deployment and Service
        run: |
          kubectl --kubeconfig=kubeconfig.yaml apply -f rhp-website-fe-dev-deployment-service.yaml -n ${{ env.K8S_NAMESPACE }}